# THIS FILE IS AUTOMATICALLY GENERATED.
"""
Calm DSL for Terraform EKS Cluster blueprint

"""

import base64
import os
import json
from calm.dsl.builtins import *
from calm.dsl.config import get_context

ContextObj = get_context()
init_data = ContextObj.get_init_config()

if file_exists(os.path.join(init_data["LOCAL_DIR"]["location"], "nutanix_key_user")):
    NutanixKeyUser = read_local_file("nutanix_key_user")
else:
    NutanixKeyUser = "nutanix"

if file_exists(os.path.join(init_data["LOCAL_DIR"]["location"], "nutanix_user")):
    NutanixUser = read_local_file("nutanix_user")
else:
    NutanixUser = "nutanix"

if file_exists(os.path.join(init_data["LOCAL_DIR"]["location"], "prism_central_user")):
    PrismCentralUser = read_local_file("prism_central_user")
else:
    PrismCentralUser = "admin"

if file_exists(os.path.join(init_data["LOCAL_DIR"]["location"], "prism_element_user")):
    PrismElementUser = read_local_file("prism_element_user")
else:
    PrismElementUser = "admin"

NutanixPublicKey = read_local_file("nutanix_public_key")
NutanixKey = read_local_file("nutanix_key")

NutanixCred = basic_cred(
        NutanixKeyUser,
        name="Nutanix",
        type="KEY",
        password=NutanixKey,
        default=True
    )

NutanixPassword = read_local_file("nutanix_password")
NutanixPasswordCred = basic_cred(
        NutanixUser,
        name="Nutanix Password",
        type="PASSWORD",
        password=NutanixPassword,
        default=True
    )

PrismCentralPassword = read_local_file("prism_central_password")
PrismCentralCred = basic_cred(
        PrismCentralUser,
        name="Prism Central User",
        type="PASSWORD",
        password=PrismCentralPassword,
        default=False
    )

EncrypedPrismCentralCreds = base64.b64encode(bytes(PrismCentralPassword, 'utf-8'))

# PrismElementPassword = read_local_file("prism_element_password")
# PrismElementCred = basic_cred(
#         PrismElementUser,
#         name="Prism Element User",
#         type="PASSWORD",
#         password=PrismElementPassword,
#         default=False
#     )

# EncrypedPrismElementCreds = base64.b64encode(bytes(PrismElementPassword, 'utf-8'))

EksServiceAccountUser = read_local_file("aws_access_key_id")
EksServiceAccountPassword = read_local_file("aws_secret_access_key")
EksServiceAccountCred = basic_cred(
        EksServiceAccountUser,
        name="Eks Service Account User",
        type="PASSWORD",
        password=EksServiceAccountPassword,
        default=False
    )


# OS Image details for VM
# Centos74_Image = vm_disk_package(
#         name="centos7_generic",
#         config_file="image_configs/centos74_disk.yaml"
#     )

KarbonctlEnpoint = os.getenv("KARBONCTL_WS_ENDPOINT")

class Eks_WorkstationService(Service):
    """Workstation Service"""

    # @action
    # def InstallDocker(name="Install Docker"):
    #     CalmTask.Exec.ssh(
    #         name="Intall Docker",
    #         filename="../_common/centos/scripts/install_docker.sh",
    #         cred=NutanixCred
    #     )
    #     CalmTask.Exec.ssh(
    #         name="Intall Docker Compose",
    #         filename="../_common/centos/scripts/install_docker_compose.sh",
    #         cred=NutanixCred
    #     )

    # @action
    # def InstallKubeCTL(name="Install kubectl"):
    #     CalmTask.Exec.ssh(
    #         name="Install Kube CTL",
    #         filename="../_common/centos/scripts/install_kubectl.sh",
    #         cred=NutanixCred
    #     )
    #     CalmTask.Exec.ssh(
    #         name="Configure Kubectl Aliases",
    #         filename="../_common/centos/scripts/configure_kubectl_aliases.sh",
    #         cred=NutanixCred
    #     )
    #     CalmTask.Exec.ssh(
    #         name="Install Kubectx and Kubens",
    #         filename="../_common/centos/scripts/install_kubectx_kubens.sh",
    #         cred=NutanixCred
    #     )
    #     CalmTask.Exec.ssh(
    #         name="Install Kube PS1",
    #         filename="../_common/centos/scripts/install_kube-ps1.sh",
    #         cred=NutanixCred
    #     )
    #     CalmTask.Exec.ssh(
    #         name="Install Kubectl Krew Package Manager",
    #         filename="../_common/centos/scripts/install_kubectl_krew.sh",
    #         cred=NutanixCred
    #     )
    #     CalmTask.Exec.ssh(
    #         name="Install Stern",
    #         filename="../_common/centos/scripts/install_stern.sh",
    #         cred=NutanixCred
    #     )
    #     CalmTask.Exec.ssh(
    #         name="Install JQ",
    #         filename="../_common/centos/scripts/install_jq.sh",
    #         cred=NutanixCred
    #     )

    # @action
    # def InstallPackages(name="Install Packages"):
    #     CalmTask.Exec.ssh(
    #         name="Install Packages",
    #         filename="../_common/centos/scripts/install_required_packages.sh",
    #         cred=NutanixCred
    #     )
    #     CalmTask.Exec.ssh(
    #         name="Install Helm",
    #         filename="../_common/centos/scripts/install_helm.sh",
    #         cred=NutanixCred
    #     )

    # @action
    # def InstallVim(name="Install Vim"):
    #     CalmTask.Exec.ssh(
    #         name="Install Vim",
    #         filename="../_common/centos/scripts/install_vim.sh",
    #         cred=NutanixCred
    #     )

    # @action
    # def ConfigureUser(name="Configure User"):
    #     CalmTask.Exec.ssh(
    #         name="Configure User",
    #         filename="../_common/centos/scripts/configure_user.sh",
    #         cred=NutanixCred
    #     )

    # @action
    # def InstallTerraform(name="Install Terraform"):
    #     CalmTask.Exec.ssh(
    #         name="Install Terraform",
    #         filename="../_common/centos/scripts/install_terraform.sh",
    #         cred=NutanixCred
    #     )
    #     CalmTask.Exec.ssh(
    #         name="Install GoLang",
    #         filename="../_common/centos/scripts/install_golang.sh",
    #         cred=NutanixCred
    #     )

    @action
    def DeployEKSCluster(name="Deploy EKS"):
        CalmTask.Exec.ssh(
            name="Clone EKS Terraform Repo",
            filename="scripts/terraform_deploy/clone_repo.sh",
            cred=NutanixCred
        )
        CalmTask.Exec.ssh(
            name="Initialize Terraform",
            filename="scripts/terraform_deploy/initialize_terraform.sh",
            cred=NutanixCred
        )
        CalmTask.Exec.ssh(
            name="Apply Terraform",
            filename="scripts/terraform_deploy/terraform_apply.sh",
            cred=NutanixCred
        )
        CalmTask.Exec.ssh(
            name="Validate EKS",
            filename="scripts/terraform_deploy/validate_k8s_cluster.sh",
            cred=NutanixCred
        )


    @action
    def Eks_Scale_In_Cluster():
        ScaleIn = CalmVariable.Simple.int(
            "1",
            label="",
            regex="^[\d]*$",
            validate_regex=False,
            is_mandatory=True,
            is_hidden=False,
            runtime=True,
            description="",
        )
        CalmTask.Exec.ssh(
            name="Scale_In_Cluster",
            filename="scripts/day_two_actions/terraform_scale_in.sh",
            cred=NutanixCred
        )

    @action
    def Eks_Scale_Out_Cluster():
        ScaleOut = CalmVariable.Simple.int(
            "1",
            label="",
            regex="^[\d]*$",
            validate_regex=False,
            is_mandatory=True,
            is_hidden=False,
            runtime=True,
            description="",
        )
        CalmTask.Exec.ssh(
            name="Scale_Out_Cluster",
            filename="scripts/day_two_actions/terraform_scale_out.sh",
            cred=NutanixCred
        )


    # @action
    # def Eks_Upgrade_Cluster():

    #     CalmTask.Exec.ssh(
    #         filename="scripts/anthos_upgrade_cluster.sh",
    #         name="Upgrade_Cluster"
    #     )

    @action
    def Eks_Destroy_Cluster():

        CalmTask.Exec.ssh(
            name="Eks_Destroy_Cluster",
            filename="scripts/day_two_actions/terraform_destroy.sh",
            cred=NutanixCred
        )

    @action
    def __delete__():
        """System action for deleting an application. Deletes created VMs as well"""

        Eks_WorkstationService.Eks_Destroy_Cluster(name="Eks_Destroy_Cluster")


class Eks_WorkstationPackage(Package):
    """Workstation Package"""

    # Services created by installing this Package
    services = [ref(Eks_WorkstationService)]

    @action
    def __install__():
        # Eks_WorkstationService.ConfigureUser(name="Configure User")
        # Eks_WorkstationService.InstallDocker(name="Install Docker")
        # Eks_WorkstationService.InstallKubeCTL(name="Install KubeCTL")
        # Eks_WorkstationService.InstallPackages(name="Install Required Packages")
        # Eks_WorkstationService.InstallVim(name="Install Vim")
        # Eks_WorkstationService.InstallTerraform(name="Install Terraform")
        Eks_WorkstationService.DeployEKSCluster(name="Deploy EKS Cluster")


# class Eks_WorkstationVmResources(AhvVmResources):

#     memory = 4
#     vCPUs = 2
#     cores_per_vCPU = 1
#     disks = [
#         AhvVmDisk.Disk.Scsi.cloneFromVMDiskPackage(Centos74_Image, bootable=True)
#     ]
#     nics = [
#         AhvVmNic.NormalNic(os.getenv("IPAM_VLAN")),
#     ]

#     boot_type = "BIOS"

#     guest_customization = AhvVmGC.CloudInit(filename="scripts/guest_customizations/guest_cus.yaml")

# class Eks_WorkstationVm(AhvVm):

#     resources = Eks_WorkstationVmResources
#     categories = {"AppFamily": "Demo", "AppType": "Default"}


class Eks_WorkstationSubstrate(Substrate):
    name = "EKS Admin Workstation VM"

    # provider_spec = Eks_WorkstationVm
    # provider_spec.name = "eks-admin-workstation-@@{calm_unique}@@"

    # os_type = "Linux"
    # readiness_probe = {
    #     "disabled": False,
    #     "delay_secs": "15",
    #     "connection_type": "SSH",
    #     "connection_port": 22,
    #     "credential": ref(NutanixCred),
    # }

    # @action
    # def __pre_create__():
    #     CalmTask.SetVariable.escript(
    #         name="Set Lowercase App Name",
    #         filename="../_common/centos/scripts/set_lower_case_app_name.py",
    #         variables=["app_name"],
    #     )

    os_type = "Linux"
    provider_type = "EXISTING_VM"
    provider_spec = read_provider_spec(os.path.join("image_configs", "karbonctl_workstation_provider_spec.yaml"))

    provider_spec.spec["address"] = KarbonctlEnpoint

    readiness_probe = readiness_probe(
        connection_type="SSH",
        disabled=False,
        retries="5",
        connection_port=22,
        address=KarbonctlEnpoint,
        delay_secs="60",
        credential=ref(NutanixCred),
    )


class Eks_WorkstationDeployment(Deployment):
    """Workstation Deployment"""

    packages = [ref(Eks_WorkstationPackage)]
    substrate = ref(Eks_WorkstationSubstrate)


class Eks_WorkstationProfile(Profile):

    # Deployments under this profile
    deployments = [Eks_WorkstationDeployment]

    nutanix_public_key = CalmVariable.Simple.Secret(
        NutanixPublicKey,
        label="Nutanix Public Key",
        is_hidden=True,
        description="SSH public key for the Nutanix user."
    )
    pc_instance_port = CalmVariable.Simple.string(
        "9440",
        label="Prism Central Port Number",
        is_mandatory=True,
        runtime=True,
        description="IP address of the Prism Central instance that manages this Calm instance."
    )
    pc_instance_ip = CalmVariable.Simple.string(
        os.getenv("PC_IP_ADDRESS"),
        label="Prism Central IP",
        is_mandatory=True,
        runtime=True,
        description="IP address of the Prism Central instance that manages this Calm instance."
    )

    @action
    def ScaleOut():
        """This action will scale out worker nodes by given scale out count"""

        ScaleOut = CalmVariable.Simple.int(
            "1",
            label="",
            regex="^[\d]*$",
            validate_regex=False,
            is_mandatory=True,
            is_hidden=False,
            runtime=True,
            description="",
        )
        Eks_WorkstationService.Eks_Scale_Out_Cluster(name="Eks_Scale_Out_Cluster")

    @action
    def ScaleIn():
        """This action will scale in workder nodes by given scale in count"""

        ScaleIn = CalmVariable.Simple.int(
            "1",
            label="",
            regex="^[\d]*$",
            validate_regex=False,
            is_mandatory=True,
            is_hidden=False,
            runtime=True,
            description="",
        )
        Eks_WorkstationService.Eks_Scale_In_Cluster(name="Eks_Scale_In_Cluster")

    # @action
    # def UpgradeRke():
    #     """This action will upgrade the Rke cluster to a new version"""

    #     ANTHOS_VERSION = CalmVariable.Simple(
    #         "",
    #         label="Rke cluster version",
    #         regex="^(\d+\.)?(\d+\.)?(\*|\d+)$",
    #         validate_regex=True,
    #         is_mandatory=True,
    #         is_hidden=False,
    #         runtime=True,
    #         description="The only supported version is 1.6.1, but 1.6.2 or 1.7.0 can be tested.",
    #     )
    #     AdminVM.Eks_Upgrade_Cluster(name="Eks_Upgrade_Cluster")


class Eks_Workstation(Blueprint):
    """ Blueprint for Eks_Workstation app using AHV VM"""

    credentials = [
            NutanixCred,
            NutanixPasswordCred,
            PrismCentralCred,
            EksServiceAccountCred,
    ]
    services = [Eks_WorkstationService]
    packages = [Eks_WorkstationPackage]
    substrates = [Eks_WorkstationSubstrate]
    profiles = [Eks_WorkstationProfile]
